services:
  - type: web
    name: ai-company-bot
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python3 app.py
    envVars:
      - key: LLM
        value: gemini
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: GEMINI_API_KEY
        sync: false
